<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="true" %>
<%
    com.example.pahanaeduwebapp.model.User user =
            (com.example.pahanaeduwebapp.model.User) session.getAttribute("user");

    if (user == null || !"admin".equalsIgnoreCase(user.getRole())) {
        response.sendRedirect("${pageContext.request.contextPath}/login.jsp");
        return;
    }
%>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="${pageContext.request.contextPath}/assets/bootstrap/css/bootstrap.min.css">
</head>
<body class="d-flex flex-column" style="min-height: 100vh; margin-left: 70px;">

<!-- Reusable Header -->
<%@ include file="/components/header.jsp" %>

<%@ include file="/components/sidebar.jsp" %>

<main class="flex-grow-1 p-4">
    <div class="container mt-2 mb-4">
        <h2 class="mb-4"><i class="bi bi-shield-lock-fill me-2 text-primary"></i>Admin Dashboard</h2>
        <div class="row g-4">

            <!-- Manage Users -->
            <div class="col-md-4">
                <div class="card shadow-sm border-0 h-100 bg-primary-subtle">
                    <div class="card-body">
                        <h5 class="card-title"><i class="bi bi-person-gear me-2"></i> Manage Users</h5>
                        <p class="card-text">Create, update, or remove admin and staff user accounts.</p>
                        <a href="${pageContext.request.contextPath}/admin/users" class="btn btn-primary" style="width: 70px;">Go</a>
                    </div>
                </div>
            </div>

            <!-- Manage Items -->
            <div class="col-md-4">
                <div class="card shadow-sm border-0 h-100 bg-success-subtle">
                    <div class="card-body">
                        <h5 class="card-title"><i class="bi bi-journal-bookmark-fill me-2"></i> Manage Items</h5>
                        <p class="card-text">Add, edit, or delete inventory including books and stationery.</p>
                        <a href="${pageContext.request.contextPath}/admin/items" class="btn btn-primary" style="width: 70px;">Go</a>
                    </div>
                </div>
            </div>

            <!-- View Bills -->
            <div class="col-md-4">
                <div class="card shadow-sm border-0 h-100 bg-info-subtle">
                    <div class="card-body">
                        <h5 class="card-title"><i class="bi bi-receipt-cutoff me-2"></i> View Bills</h5>
                        <p class="card-text">Access, print, or delete customer bills generated by staff.</p>
                        <a href="${pageContext.request.contextPath}/admin/billing/bills" class="btn btn-primary" style="width: 70px;">Go</a>
                    </div>
                </div>
            </div>

            <!-- Reports -->
            <div class="col-md-4">
                <div class="card shadow-sm border-0 h-100 bg-warning-subtle">
                    <div class="card-body">
                        <h5 class="card-title"><i class="bi bi-graph-up-arrow me-2"></i> Reports</h5>
                        <p class="card-text">View billing activity, staff performance, and revenue reports.</p>
                        <a href="${pageContext.request.contextPath}/admin/reports" class="btn btn-primary" style="width: 70px;">View</a>
                    </div>
                </div>
            </div>

            <!-- Audit Logs -->
            <div class="col-md-4">
                <div class="card shadow-sm border-0 h-100 bg-danger-subtle">
                    <div class="card-body">
                        <h5 class="card-title"><i class="bi bi-clock-history me-2"></i> Audit Logs</h5>
                        <p class="card-text">Track login/logout history of users or clear audit entries.</p>
                        <a href="${pageContext.request.contextPath}/admin/auditLogs" class="btn btn-primary" style="width: 70px;">Go</a>
                    </div>
                </div>
            </div>

            <!-- Help Guide -->
            <div class="col-md-4">
                <div class="card shadow-sm border-0 h-100 bg-secondary-subtle">
                    <div class="card-body">
                        <h5 class="card-title"><i class="bi bi-question-circle-fill me-2"></i> Admin Help Guide</h5>
                        <p class="card-text">Learn how to use the system effectively with step-by-step guidance.</p>
                        <a href="${pageContext.request.contextPath}/admin/help.jsp" class="btn btn-primary" style="width: 70px;">View</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<!-- Reusable Footer -->
<%@ include file="/components/footer.jsp" %>
</body>
</html>
